// Auto-generated by `supabase gen types typescript` once first migration lands.
// Stub for PR2 — no tables yet.
// Regenerate with: pnpm supabase:types
export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
